defaultBaseImage: public.ecr.aws/lambda/provided:al2023
defaultPlatforms:
- linux/amd64
builds:
  - id: main
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64